name:                gnucash
version:             0.1.0.0
github:              "groscoe/haskell-gnucash"
license:             MIT
author:              "Gustavo Roscoe"
maintainer:          "gustavo@gustavoroscoe.com"
copyright:           "2021 Gustavo Roscoe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Parse, build and manipulate GnuCash files
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/groscoe/haskell-gnucash#readme>

dependencies:
  - base >= 4.7 && < 5
  - Decimal              >= 0.5.1 && < 0.6
  - bytestring           >= 0.10.12 && < 0.11
  - exceptions           >= 0.10.4 && < 0.11
  - hxt                  >= 9.3.1 && < 9.4
  - time                 >= 1.9.3 && < 1.10
  - text                 >= 1.2.4 && < 1.3
  - magic                >= 1.1 && < 1.2
  - temporary            >= 1.3 && < 1.4
  - unordered-containers >= 0.2.13 && < 0.3
  - zlib                 >= 0.6.2 && < 0.7

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat

tests:
  gnucash-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - gnucash
    - doctest
